<a href="https://colab.research.google.com/github/CamiloCarvajalAraya/Tareas-de-Bootcamps-Chile/blob/main/Ejercicio_Panaderia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INTRODUCCION A NUMPY

Para dirigir nuestra exploración por Python, usaremos un proyecto sencillo basado en datos. Supongamos unos jóvenes de un club de tecnología les pidió ayuda para analizar datos de su venta de pasteles.  Esperan reunir $200.  

In [ ]:
Lista_Precio = [2,1,10] # Precios de Brownie- Galleta - Pastel
Lista_Cantidad = [17, 40 , 1]
Costo_Producto = [0.25,0.50,5.00] 

import numpy as np # El siguiente codigo sirve para importar la biblioteca Numpy.

Lista_Precio_Array = np.array(Lista_Precio)
Lista_Cantidad_Array = np.array(Lista_Cantidad)
print(Lista_Precio_Array)
print(Lista_Cantidad_Array)
Ventas_Totales_1 = Lista_Precio_Array * Lista_Cantidad_Array
print(Ventas_Totales_1)
Costo_Producto_Array = np.array(Costo_Producto)
Utilidad_Unitaria = Lista_Precio_Array - Costo_Producto_Array
print(Utilidad_Unitaria)

Lista_Precio_Array = np.append(Lista_Precio_Array,7) # Procedimiento para agregar el Precio ($7) de una tarta.
print(Lista_Precio_Array)

Lista_Precio_Array = np.append(Lista_Precio_Array,[4.50,3,4,9]) # Procedimiento para agregar el precio de Dulces- Magdalena- Pan- Torta
print(Lista_Precio_Array)

Lista_Precio_Array = np.delete(Lista_Precio_Array,-1) # Se eliminan las tortas
print(Lista_Precio_Array)

Lista_Precio_Array[2] = 12
print(Lista_Precio_Array)

#Hagamos un resumen de las arrays que utilizaremos:

Lista_Precio_Array
print(Lista_Precio_Array) # Precios de Brownie- Galleta - Pastel - Tarta-Dulces- Magdalena- Pan
Lista_Cantidad_Array
print(Lista_Cantidad_Array)

# Etapa N°2

Lista_Cantidad_Array_Actualizada = np.append(Lista_Cantidad_Array,[2,3,16,5])
print(Lista_Cantidad_Array_Actualizada)
Lista_Cantidad_Array_Actualizada[1]= 39
print(Lista_Cantidad_Array_Actualizada) 

# Etapa N°3

Ventas_Totales_2 = Lista_Cantidad_Array_Actualizada * Lista_Precio_Array
print(Ventas_Totales_2)

# Etapa 4

Inventario = [0,0,2,1,6,0,2]
Inventario_Array = np.array(Inventario)

# Etapa 5


Liquidacion_Array = (Lista_Precio_Array /2) * (Inventario_Array)
print(Liquidacion_Array)

#Etapa 6


Venta_Totales_3 = Ventas_Totales_2 + Liquidacion_Array
print(Venta_Totales_3)

Venta_Totales_4 = np.sum(Venta_Totales_3)
print(Venta_Totales_4)






















































[ 2  1 10]
[17 40  1]
[34 40 10]
[1.75 0.5  5.  ]
[ 2  1 10  7]
[ 2.   1.  10.   7.   4.5  3.   4.   9. ]
[ 2.   1.  10.   7.   4.5  3.   4. ]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[17 40  1]
[17 40  1  2  3 16  5]
[17 39  1  2  3 16  5]
[34.  39.  12.  14.  13.5 48.  20. ]
[ 0.   0.  12.   3.5 13.5  0.   4. ]
[34.  39.  24.  17.5 27.  48.  24. ]
213.5
